### ISSUE TITLE
possible typo in graylog2.js line 118

### ISSUE THREAD

**Issue by declansto** [Wizcorp/node-graylog2#25]
line 112 - 121
 
   var payload,
        fileinfo,
        that    = this,
        field   = '',
        message = {
            version    : '1.0',
    118 -->>       timestamp  : (timestamp || new Date()).getTime() / 1000, <<--
            host       : this.hostname,
            facility   : this.facility,
            level      : level
        };

**Comment by ronkorving** [comment]
I assume you mean to say that timestamp is a number, and this code runs `.getTime()` on it? I think the original author of that line probably intended for that argument to be a `Date` object. But I think you're right, it's more natural to support a number than it is a `Date` object, although both could easily be supported.

Can you confirm if I understood you correctly?

**Comment by declansto** [comment]
My comment was that I needed to remove the '(' in timestamp : ( timestamp || .. before the code would run. This looks like a typo in the code.

**Comment by ronkorving** [comment]
The code does not have a brace too many. It wouldn't run if that were the case, and this module does run.

Am I misunderstanding? Can you double check?

**Comment by declansto** [comment]
/home/wizrd/ic-schedulergraphrunner/node_modules/graylog2/graylog.js:118
            timestamp  : (timestamp || new Date()).getTime() / 1000,
                                                   ^

TypeError: (timestamp || (intermediate value)).getTime is not a function
    at graylog.log [as _log] (/home/wizrd/ic-schedulergraphrunner/node_modules/graylog2/graylog.js:118:52)
    at graylog.error (/home/wizrd/ic-schedulergraphrunner/node_modules/graylog2/graylog.js:88:17)
    at processNewGraphs (/home/wizrd/ic-schedulergraphrunner/furoMCR.js:296:32)
    at Request._callback (/home/wizrd/ic-schedulergraphrunner/furoMCR.js:186:17)
    at Request.self.callback (/home/wizrd/ic-schedulergraphrunner/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/wizrd/ic-schedulergraphrunner/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)

**Comment by ronkorving** [comment]
I think the idea is that you pass a `Date` instance, not a number.
