### ISSUE TITLE
Logging error object fails

### ISSUE THREAD

**Issue by michaelw85** [Wizcorp/node-graylog2#46]
```
TypeError: Cannot read property 'split' of undefined
    at graylog.log [as _log] (/Users/.....node_modules/graylog2/graylog.js:146:34)
    at graylog.error (/Users/.....node_modules/graylog2/graylog.js:93:17)
```

Graylog code:

```js
    } else if (short_message.stack && short_message.message) {

        // Short message is an Error message, we process accordingly
        message.short_message = short_message.message;
        message.full_message  = short_message.stack;

        // extract error file and line
        fileinfo = message.stack.split('\n')[0];
```
Looking at this, the last line `message.stack` should be `short_message.stack`. 
Message is a newly build object within the library which does not contain a stack trace by default.

**Comment by michaelw85** [comment]
I see this is already fixed & merged (commit 82532a6b1fa0e74a05497cd33921a90eebaa683c) but not released yet. Could this be released @ronkorving 😄

**Comment by bendavis78** [comment]
I am also seeing this issue. Any reason this hasn't been released?

**Comment by mb-realpage** [comment]
+1 from me. A quick glance at the code immediately showed the problem. Is this project looking for a new owner?
